name: Node.js CI and Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    # Set up Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Install dependencies
    - run: npm ci

    # Build the app
    - run: CI=false npm run build --if-present

    # Upload the build artifacts to be used for GitHub Pages
    - name: Upload artifact for GitHub Pages
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./build # Upload the build folder where your static files are generated

  deploy:
    # This job runs only after the `build` job completes successfully
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    # Deploy to GitHub Pages
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
